version: '3'

services:
  ganache:
    image: trufflesuite/ganache:latest
    ports:
      - "8546:8546"
    command: >
      -h 0.0.0.0
      -p 8546
      --chain.networkId=5777
      --wallet.defaultBalance=1000
      --miner.blockGasLimit="0x1c9c380" 
      --wallet.totalAccounts=10000
      --wallet.accountKeysPath="/shared/accounts.json"
    volumes:
      - shared_data:/shared
    networks:
      - mynetwork

  supernova:
    build: .
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "20101:5000"
    environment:
      - EXTERNAL_RPC_URL=http://3.34.91.236:20101/interact
      - WEB3_PROVIDER_URI=http://ganache:8546
    restart: unless-stopped
    depends_on:
      - ganache
    volumes:
      - shared_data:/shared
      - flag.txt:/flag.txt:ro
    networks:
      - mynetwork

volumes:
  shared_data:
  flag.txt:

networks:
  mynetwork:
    driver: bridge
